-- Schema terbaru untuk setup BARU.
-- Jika database kamu sudah ada dan migration v2 sudah dijalankan, tidak perlu menjalankan file ini ulang.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_id text not null,
  name_en text not null,
  name_ja text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.works (
  id bigint generated by default as identity primary key,
  title_id text not null,
  title_en text,
  title_ja text,
  description_id text,
  description_en text,
  description_ja text,
  category_id bigint references public.categories(id) on update cascade on delete restrict,
  project_start_date date,
  project_end_date date,
  project_sort_date date not null default current_date,
  image_path text,
  image_url text,
  tools text[] default '{}',
  show_on_home boolean not null default false,
  home_order integer,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint works_valid_project_dates check (
    project_end_date is null
    or project_start_date is null
    or project_end_date >= project_start_date
  ),
  constraint works_has_image check (
    image_url is not null or image_path is not null
  )
);

insert into public.categories (slug, name_id, name_en, name_ja, sort_order)
values
  ('social-media', 'Media Sosial', 'Social Media', 'SNSデザイン', 1),
  ('logo', 'Logo', 'Logo Design', 'ロゴデザイン', 2),
  ('branding', 'Branding', 'Branding', 'ブランディング', 3),
  ('poster', 'Poster', 'Poster', 'ポスター', 4),
  ('banner', 'Banner', 'Banner', 'バナー', 5),
  ('mockup-print', 'Mockup / Cetak', 'Mockup / Print', 'モックアップ・印刷', 6),
  ('educational-material', 'Materi Ajar', 'Educational Material', '教材', 7),
  ('website', 'Website / Interaktif', 'Website / Interactive', 'Web・インタラクティブ', 8),
  ('photography', 'Fotografi', 'Photography', '写真', 9),
  ('other', 'Lainnya', 'Other', 'その他', 99)
on conflict (slug) do update set
  name_id = excluded.name_id,
  name_en = excluded.name_en,
  name_ja = excluded.name_ja,
  sort_order = excluded.sort_order;

create or replace function public.sync_work_sort_date()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.project_sort_date := coalesce(
    new.project_end_date,
    new.project_start_date,
    (new.created_at at time zone 'UTC')::date,
    current_date
  );
  return new;
end;
$$;

create or replace function public.set_work_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_works_sync_sort_date on public.works;
create trigger trg_works_sync_sort_date
before insert or update of project_start_date, project_end_date, created_at
on public.works
for each row execute function public.sync_work_sort_date();

drop trigger if exists trg_works_updated_at on public.works;
create trigger trg_works_updated_at
before update on public.works
for each row execute function public.set_work_updated_at();

create index if not exists works_home_index
on public.works (home_order)
where is_published = true and show_on_home = true;

create index if not exists works_date_index
on public.works (project_sort_date desc)
where is_published = true;

create index if not exists works_category_date_index
on public.works (category_id, project_sort_date desc)
where is_published = true;

alter table public.categories enable row level security;
alter table public.works enable row level security;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories"
on public.categories for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Public can read published works" on public.works;
create policy "Public can read published works"
on public.works for select
to anon, authenticated
using (is_published = true);
