-- MALDY PORTFOLIO — PROFILE + ACTIVITY + RELATED WORKS
begin;

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profile (
  id smallint primary key default 1 check (id = 1),
  name text not null default 'Maldy Rais',
  nickname text not null default 'Maldy Sensei',
  headline_id text, headline_en text, headline_ja text,
  bio_id text, bio_en text, bio_ja text,
  location text, email text,
  instagram_url text, behance_url text, github_url text, linkedin_url text, cv_url text,
  avatar_path text, avatar_url text,
  roles text[] not null default '{}',
  tools text[] not null default '{}',
  interests text[] not null default '{}',
  japanese_level text,
  is_published boolean not null default true,
  updated_at timestamptz not null default now()
);
alter table public.profile enable row level security;
drop policy if exists "Public can read profile" on public.profile;
create policy "Public can read profile" on public.profile for select to anon, authenticated using (is_published = true);
drop policy if exists "Admin can read all profile" on public.profile;
create policy "Admin can read all profile" on public.profile for select to authenticated using ((select public.is_portfolio_admin()));
drop policy if exists "Admin can insert profile" on public.profile;
create policy "Admin can insert profile" on public.profile for insert to authenticated with check ((select public.is_portfolio_admin()));
drop policy if exists "Admin can update profile" on public.profile;
create policy "Admin can update profile" on public.profile for update to authenticated using ((select public.is_portfolio_admin())) with check ((select public.is_portfolio_admin()));
drop trigger if exists trg_profile_updated_at on public.profile;
create trigger trg_profile_updated_at before update on public.profile for each row execute function public.set_updated_at();

insert into public.profile (
  id, name, nickname, headline_id, bio_id, location, roles, tools, interests, japanese_level
) values (
  1,
  'Maldy Rais',
  'Maldy Sensei',
  'Desainer Grafis, Tutor Bahasa Jepang, dan Creative Technologist',
  'Mahasiswa Bahasa dan Sastra Jepang, tutor bahasa Jepang, serta kreator visual yang tertarik pada desain media sosial, fotografi, dan pengalaman web interaktif.',
  'Surabaya, Indonesia',
  array['Graphic Designer','Japanese Language Tutor','Creative Technologist'],
  array['Photoshop','Illustrator','Canva','Figma','VS Code'],
  array['Graphic Design','Japanese Language','Photography','Interactive Web'],
  'Sekitar JLPT N3 (belum bersertifikat)'
) on conflict (id) do nothing;

create table if not exists public.activity_groups (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title_id text not null, title_en text, title_ja text,
  type text,
  summary_id text, summary_en text, summary_ja text,
  start_date date not null, end_date date,
  accent text,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activity_groups_valid_dates check (end_date is null or end_date >= start_date)
);
alter table public.activity_groups enable row level security;
drop policy if exists "Public can read activity groups" on public.activity_groups;
create policy "Public can read activity groups" on public.activity_groups for select to anon, authenticated using (is_published = true);
drop policy if exists "Admin can read all activity groups" on public.activity_groups;
create policy "Admin can read all activity groups" on public.activity_groups for select to authenticated using ((select public.is_portfolio_admin()));
drop policy if exists "Admin can insert activity groups" on public.activity_groups;
create policy "Admin can insert activity groups" on public.activity_groups for insert to authenticated with check ((select public.is_portfolio_admin()));
drop policy if exists "Admin can update activity groups" on public.activity_groups;
create policy "Admin can update activity groups" on public.activity_groups for update to authenticated using ((select public.is_portfolio_admin())) with check ((select public.is_portfolio_admin()));
drop policy if exists "Admin can delete activity groups" on public.activity_groups;
create policy "Admin can delete activity groups" on public.activity_groups for delete to authenticated using ((select public.is_portfolio_admin()));
drop trigger if exists trg_activity_groups_updated_at on public.activity_groups;
create trigger trg_activity_groups_updated_at before update on public.activity_groups for each row execute function public.set_updated_at();

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.activity_groups(id) on delete restrict,
  parent_activity_id bigint references public.activities(id) on delete set null,
  activity_type text,
  slug text unique,
  title_id text not null, title_en text, title_ja text,
  role_id text, role_en text, role_ja text,
  summary_id text, summary_en text, summary_ja text,
  description_id text, description_en text, description_ja text,
  start_date date not null, end_date date,
  location text,
  cover_path text, cover_url text,
  is_highlighted boolean not null default false,
  is_published boolean not null default true,
  sort_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint activities_valid_dates check (end_date is null or end_date >= start_date)
);

create or replace function public.sync_activity_sort_date()
returns trigger language plpgsql set search_path = public as $$
begin
  new.sort_date := coalesce(new.end_date, new.start_date, current_date);
  return new;
end;
$$;
drop trigger if exists trg_activities_sort_date on public.activities;
create trigger trg_activities_sort_date before insert or update of start_date, end_date on public.activities for each row execute function public.sync_activity_sort_date();
drop trigger if exists trg_activities_updated_at on public.activities;
create trigger trg_activities_updated_at before update on public.activities for each row execute function public.set_updated_at();

alter table public.activities enable row level security;
drop policy if exists "Public can read activities" on public.activities;
create policy "Public can read activities" on public.activities for select to anon, authenticated using (is_published = true);
drop policy if exists "Admin can read all activities" on public.activities;
create policy "Admin can read all activities" on public.activities for select to authenticated using ((select public.is_portfolio_admin()));
drop policy if exists "Admin can insert activities" on public.activities;
create policy "Admin can insert activities" on public.activities for insert to authenticated with check ((select public.is_portfolio_admin()));
drop policy if exists "Admin can update activities" on public.activities;
create policy "Admin can update activities" on public.activities for update to authenticated using ((select public.is_portfolio_admin())) with check ((select public.is_portfolio_admin()));
drop policy if exists "Admin can delete activities" on public.activities;
create policy "Admin can delete activities" on public.activities for delete to authenticated using ((select public.is_portfolio_admin()));

create index if not exists activities_group_date_index on public.activities (group_id, start_date);
create index if not exists activities_public_date_index on public.activities (start_date) where is_published = true;

create table if not exists public.activity_work_links (
  activity_id bigint not null references public.activities(id) on delete cascade,
  work_id bigint not null references public.works(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (activity_id, work_id)
);
alter table public.activity_work_links enable row level security;
drop policy if exists "Public can read published activity work links" on public.activity_work_links;
create policy "Public can read published activity work links"
on public.activity_work_links for select to anon, authenticated
using (
  exists (select 1 from public.activities a where a.id = activity_id and a.is_published = true)
  and exists (select 1 from public.works w where w.id = work_id and w.is_published = true)
);
drop policy if exists "Admin can read all activity work links" on public.activity_work_links;
create policy "Admin can read all activity work links" on public.activity_work_links for select to authenticated using ((select public.is_portfolio_admin()));
drop policy if exists "Admin can insert activity work links" on public.activity_work_links;
create policy "Admin can insert activity work links" on public.activity_work_links for insert to authenticated with check ((select public.is_portfolio_admin()));
drop policy if exists "Admin can delete activity work links" on public.activity_work_links;
create policy "Admin can delete activity work links" on public.activity_work_links for delete to authenticated using ((select public.is_portfolio_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portfolio-assets','portfolio-assets',true,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admin can read portfolio assets" on storage.objects;
create policy "Admin can read portfolio assets" on storage.objects for select to authenticated
using (bucket_id = 'portfolio-assets' and (select public.is_portfolio_admin()));
drop policy if exists "Admin can upload portfolio assets" on storage.objects;
create policy "Admin can upload portfolio assets" on storage.objects for insert to authenticated
with check (bucket_id = 'portfolio-assets' and (select public.is_portfolio_admin()));
drop policy if exists "Admin can update portfolio assets" on storage.objects;
create policy "Admin can update portfolio assets" on storage.objects for update to authenticated
using (bucket_id = 'portfolio-assets' and (select public.is_portfolio_admin()))
with check (bucket_id = 'portfolio-assets' and (select public.is_portfolio_admin()));
drop policy if exists "Admin can delete portfolio assets" on storage.objects;
create policy "Admin can delete portfolio assets" on storage.objects for delete to authenticated
using (bucket_id = 'portfolio-assets' and (select public.is_portfolio_admin()));

drop policy if exists "Admin can read work image objects" on storage.objects;
create policy "Admin can read work image objects" on storage.objects for select to authenticated
using (bucket_id = 'works' and (select public.is_portfolio_admin()));

commit;
