-- ================================================================
-- Maldy Portfolio — Work Media / Carousel
-- Run after 001-core-schema.sql and 002-admin-rls.sql.
--
-- IMPORTANT:
-- This migration assumes public.works.id is BIGINT / identity.
-- If public.works.id is UUID, change work_id BIGINT -> UUID.
-- ================================================================

begin;

create table if not exists public.work_media (
  id bigint generated by default as identity primary key,
  work_id bigint not null references public.works(id) on delete cascade,
  image_path text,
  image_url text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint work_media_image_source_check
    check (
      nullif(btrim(image_path), '') is not null
      or nullif(btrim(image_url), '') is not null
    ),

  constraint work_media_sort_order_check
    check (sort_order >= 0)
);

create index if not exists work_media_work_sort_idx
  on public.work_media (work_id, sort_order, id);

create or replace function public.set_work_media_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_work_media_updated_at on public.work_media;

create trigger trg_work_media_updated_at
before update on public.work_media
for each row
execute function public.set_work_media_updated_at();

alter table public.work_media enable row level security;

drop policy if exists "Public can read published work media"
  on public.work_media;

create policy "Public can read published work media"
on public.work_media
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.works
    where works.id = work_media.work_id
      and works.is_published = true
  )
);

-- The public policy above only exposes media from published works. Admins
-- also need SELECT access to media attached to drafts.
drop policy if exists "Authenticated can read all work media"
  on public.work_media;

drop policy if exists "Admin can read all work media"
  on public.work_media;

create policy "Admin can read all work media"
on public.work_media
for select
to authenticated
using ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can insert work media"
  on public.work_media;

drop policy if exists "Admin can insert work media"
  on public.work_media;

create policy "Admin can insert work media"
on public.work_media
for insert
to authenticated
with check ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can update work media"
  on public.work_media;

drop policy if exists "Admin can update work media"
  on public.work_media;

create policy "Admin can update work media"
on public.work_media
for update
to authenticated
using ((select public.is_portfolio_admin()))
with check ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can delete work media"
  on public.work_media;

drop policy if exists "Admin can delete work media"
  on public.work_media;

create policy "Admin can delete work media"
on public.work_media
for delete
to authenticated
using ((select public.is_portfolio_admin()));

commit;
