-- ================================================================
-- PROFILE TOOLS + PROFILE SAVE FIX
-- Run once in Supabase > SQL Editor.
--
-- Adds a structured tool/context table while keeping profile.tools
-- synchronized for backwards compatibility.
-- Also ensures authenticated admin users can upsert the profile.
-- ================================================================

-- 1) Make sure the current profile table can be managed by logged-in admin.
alter table public.profile enable row level security;

drop policy if exists "Public can read published profile v2" on public.profile;
create policy "Public can read published profile v2"
on public.profile
for select
to anon
using (is_published = true);

drop policy if exists "Authenticated can manage profile v2" on public.profile;
drop policy if exists "Admin can manage profile v2" on public.profile;
create policy "Admin can manage profile v2"
on public.profile
for all
to authenticated
using ((select public.is_portfolio_admin()))
with check ((select public.is_portfolio_admin()));

-- 2) Structured tools table.
-- profile_id intentionally has no FK so this migration stays compatible
-- whether your existing public.profile.id is integer, bigint, or another
-- numeric type. This portfolio uses profile_id = 1.
create table if not exists public.profile_tools (
  id bigint generated by default as identity primary key,
  profile_id bigint not null default 1,
  name text not null,
  icon_key text not null default 'other',
  description_id text null,
  description_en text null,
  description_ja text null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profile_tools_name_not_blank check (length(trim(name)) > 0),
  constraint profile_tools_profile_name_unique unique (profile_id, name)
);

alter table public.profile_tools
  add column if not exists icon_key text not null default 'other',
  add column if not exists description_id text null,
  add column if not exists description_en text null,
  add column if not exists description_ja text null,
  add column if not exists sort_order integer not null default 0,
  add column if not exists is_active boolean not null default true,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists profile_tools_profile_order_idx
  on public.profile_tools (profile_id, sort_order, id);

create or replace function public.set_profile_tools_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profile_tools_updated_at on public.profile_tools;
create trigger trg_profile_tools_updated_at
before update on public.profile_tools
for each row execute function public.set_profile_tools_updated_at();

-- 3) RLS.
alter table public.profile_tools enable row level security;

drop policy if exists "Public can read active profile tools" on public.profile_tools;
create policy "Public can read active profile tools"
on public.profile_tools
for select
to anon
using (is_active = true);

drop policy if exists "Authenticated can manage profile tools" on public.profile_tools;
drop policy if exists "Admin can manage profile tools" on public.profile_tools;
create policy "Admin can manage profile tools"
on public.profile_tools
for all
to authenticated
using ((select public.is_portfolio_admin()))
with check ((select public.is_portfolio_admin()));

-- 4) Copy the current legacy profile.tools array into profile_tools.
-- Existing rows are preserved.
insert into public.profile_tools (
  profile_id,
  name,
  icon_key,
  sort_order,
  is_active
)
select
  1,
  tool_name,
  case lower(tool_name)
    when 'photoshop' then 'photoshop'
    when 'adobe photoshop' then 'photoshop'
    when 'illustrator' then 'illustrator'
    when 'adobe illustrator' then 'illustrator'
    when 'figma' then 'figma'
    when 'canva' then 'canva'
    when 'vs code' then 'vscode'
    when 'visual studio code' then 'vscode'
    when 'lightroom' then 'lightroom'
    when 'adobe lightroom' then 'lightroom'
    when 'premiere pro' then 'premiere'
    when 'adobe premiere pro' then 'premiere'
    when 'after effects' then 'aftereffects'
    when 'adobe after effects' then 'aftereffects'
    when 'indesign' then 'indesign'
    when 'adobe indesign' then 'indesign'
    else 'other'
  end,
  ordinality::integer - 1,
  true
from public.profile p
cross join lateral unnest(coalesce(p.tools, '{}'::text[]))
  with ordinality as legacy(tool_name, ordinality)
where p.id = 1
on conflict (profile_id, name) do nothing;

-- 5) Helpful starter contexts for the common tools.
-- Only fills blank descriptions; your own existing text is not overwritten.
update public.profile_tools
set
  icon_key = 'photoshop',
  description_id = coalesce(description_id, 'Desain media sosial · manipulasi foto'),
  description_en = coalesce(description_en, 'Social media design · photo editing'),
  description_ja = coalesce(description_ja, 'SNSデザイン・画像編集')
where profile_id = 1
  and lower(name) in ('photoshop', 'adobe photoshop');

update public.profile_tools
set
  icon_key = 'illustrator',
  description_id = coalesce(description_id, 'Ilustrasi vektor · identitas visual'),
  description_en = coalesce(description_en, 'Vector illustration · visual identity'),
  description_ja = coalesce(description_ja, 'ベクター制作・ビジュアルアイデンティティ')
where profile_id = 1
  and lower(name) in ('illustrator', 'adobe illustrator');

update public.profile_tools
set
  icon_key = 'figma',
  description_id = coalesce(description_id, 'UI layout · prototyping'),
  description_en = coalesce(description_en, 'UI layout · prototyping'),
  description_ja = coalesce(description_ja, 'UIレイアウト・プロトタイピング')
where profile_id = 1
  and lower(name) = 'figma';

update public.profile_tools
set
  icon_key = 'canva',
  description_id = coalesce(description_id, 'Konten cepat · materi visual'),
  description_en = coalesce(description_en, 'Quick content · visual materials'),
  description_ja = coalesce(description_ja, 'コンテンツ制作・ビジュアル素材')
where profile_id = 1
  and lower(name) = 'canva';

update public.profile_tools
set
  icon_key = 'vscode',
  description_id = coalesce(description_id, 'Frontend development · eksperimen web'),
  description_en = coalesce(description_en, 'Frontend development · web experiments'),
  description_ja = coalesce(description_ja, 'フロントエンド開発・Web制作')
where profile_id = 1
  and lower(name) in ('vs code', 'visual studio code');

-- Optional verification:
-- select * from public.profile where id = 1;
-- select * from public.profile_tools where profile_id = 1 order by sort_order, id;
