-- ================================================================
-- HOME SHOWCASE SLIDER
-- Run once in Supabase SQL Editor.
-- Uses the existing public.works and public.categories tables.
-- Custom showcase uploads reuse the existing `works` Storage bucket.
-- ================================================================

create table if not exists public.home_showcase_slides (
  id bigint generated by default as identity primary key,
  title_id text not null,
  title_en text null,
  title_ja text null,
  description_id text null,
  description_en text null,
  description_ja text null,
  cta_label_id text null,
  cta_label_en text null,
  cta_label_ja text null,
  cta_url text null,
  cta_category_id bigint null references public.categories(id)
    on update cascade on delete set null,
  slide_order integer not null default 1,
  autoplay_seconds integer not null default 7,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_showcase_autoplay_range
    check (autoplay_seconds between 3 and 60),
  constraint home_showcase_order_positive
    check (slide_order >= 1)
);

create table if not exists public.home_showcase_images (
  id bigint generated by default as identity primary key,
  slide_id bigint not null references public.home_showcase_slides(id)
    on update cascade on delete cascade,
  work_id bigint null references public.works(id)
    on update cascade on delete cascade,
  image_path text null,
  image_url text null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint home_showcase_image_has_source check (
    work_id is not null or image_path is not null or image_url is not null
  ),
  constraint home_showcase_image_order_nonnegative check (sort_order >= 0)
);

create index if not exists home_showcase_slides_active_order_idx
  on public.home_showcase_slides (slide_order, id)
  where is_active = true;

create index if not exists home_showcase_images_slide_order_idx
  on public.home_showcase_images (slide_id, sort_order, id);

create or replace function public.set_home_showcase_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_home_showcase_updated_at on public.home_showcase_slides;
create trigger trg_home_showcase_updated_at
before update on public.home_showcase_slides
for each row execute function public.set_home_showcase_updated_at();

-- Public visitors only need to read active slides and their images.
alter table public.home_showcase_slides enable row level security;
alter table public.home_showcase_images enable row level security;

drop policy if exists "Public can read active showcase slides" on public.home_showcase_slides;
create policy "Public can read active showcase slides"
on public.home_showcase_slides
for select
to anon, authenticated
using (is_active = true);

drop policy if exists "Public can read images from active showcase slides" on public.home_showcase_images;
create policy "Public can read images from active showcase slides"
on public.home_showcase_images
for select
to anon, authenticated
using (
  exists (
    select 1
    from public.home_showcase_slides slide
    where slide.id = home_showcase_images.slide_id
      and slide.is_active = true
  )
);

drop policy if exists "Admin can read all showcase slides" on public.home_showcase_slides;
create policy "Admin can read all showcase slides"
on public.home_showcase_slides for select to authenticated
using ((select public.is_portfolio_admin()));

drop policy if exists "Admin can read all showcase images" on public.home_showcase_images;
create policy "Admin can read all showcase images"
on public.home_showcase_images for select to authenticated
using ((select public.is_portfolio_admin()));

-- The admin UI is a convenience layer; RLS below is the security boundary.
-- These policies allow signed-in users to maintain showcase content.
drop policy if exists "Authenticated can insert showcase slides" on public.home_showcase_slides;
create policy "Authenticated can insert showcase slides"
on public.home_showcase_slides for insert to authenticated
with check ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can update showcase slides" on public.home_showcase_slides;
create policy "Authenticated can update showcase slides"
on public.home_showcase_slides for update to authenticated
using ((select public.is_portfolio_admin())) with check ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can delete showcase slides" on public.home_showcase_slides;
create policy "Authenticated can delete showcase slides"
on public.home_showcase_slides for delete to authenticated
using ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can insert showcase images" on public.home_showcase_images;
create policy "Authenticated can insert showcase images"
on public.home_showcase_images for insert to authenticated
with check ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can update showcase images" on public.home_showcase_images;
create policy "Authenticated can update showcase images"
on public.home_showcase_images for update to authenticated
using ((select public.is_portfolio_admin())) with check ((select public.is_portfolio_admin()));

drop policy if exists "Authenticated can delete showcase images" on public.home_showcase_images;
create policy "Authenticated can delete showcase images"
on public.home_showcase_images for delete to authenticated
using ((select public.is_portfolio_admin()));

-- Optional starter slides. Uncomment and edit if you want placeholders first.
-- insert into public.home_showcase_slides
--   (title_id, description_id, slide_order, autoplay_seconds, is_active)
-- values
--   ('Mengajar & berbagi.', 'Materi dan pengalaman saya saat mengajar bahasa Jepang.', 1, 7, true),
--   ('Mendesain ide menjadi visual.', 'Pilihan karya desain dan eksplorasi visual.', 2, 7, true),
--   ('Menangkap cerita melalui gambar.', 'Potongan suasana dan momen melalui fotografi.', 3, 7, true);
